### ISSUE TITLE
saved values are getting lost

### ISSUE THREAD

**Issue by gvsrinivas1** [Crypho/cordova-plugin-secure-storage#108]
Hi, I see in frequent the saved values are getting lost when load again:

install the app and set some keys
close the app
open the app and read values.
not able to get the values.

we use the same key to open the secure storage.

Error Error: Key [_key] not found.

OS : both Android and iOS.
Tested: Android OS 6.0.1 and iOS 10.2.1

Can you try to check and let us know why this happens and any fix?

**Comment by ggozad** [comment]
I haven't seen this. Having it on both ios and android probably means you do something wrong. Could you please paste a minimal example code where this occurs?

**Comment by gvsrinivas1** [comment]
we are using only the given api function like creating namespace, setting and getting keys and removing keys..

the scenario is like this-
- creating the namespace
- set the keys and values
- continue to use the keys for some days
- then suddenly we lost the keys
and its happens in ios and android over certain time, even the namespace remains same.

**Comment by extempl** [comment]
@ggozad I assume the issue in namespace.

I see the issue on android - if you init SS with one NS, save some data, then create completely another separated instance of SS with different NS - you won't be able to read data with first instance, because the `ALIAS` will be different. Right now it only _writes_ correctly (ALIAS part is sending from the js client each write).

**Comment by ggozad** [comment]
Ah I see. Yes using various namespaces is probably not used (at least we don't use it). Would you be so kind and:
1) Write a failing test.
2) Make a pr tackling this?

**Comment by extempl** [comment]
@ggozad do you mean PR with test or with fix?

**Comment by ggozad** [comment]
Well both would be great :)
