### ISSUE TITLE
non-secure fallback

### ISSUE THREAD

**Issue by jamesdixon** [Crypho/cordova-plugin-secure-storage#129]
Hi,

Great plugin. Was just curious if you had any thought on a non-secure fallback? For context, I'm doing most development in the browser. Was thinking it might be nice to fall back to Ionic Storage or something if the app isn't running in a native environment. Thoughts? 

Thanks!

**Comment by ggozad** [comment]
Hey James,
This would be nice indeed, but it's not there. We have a mock we use internally that simply stores on localStorage but I am reluctant to provide as part of the plugin as most certainly people WILL use it.
Ideally, there should be support for the browser platform using SJCL for AES but the problem is generating and storing a key with something equivalent to the keychain which does not exist for the browser.
One could also just mock the keychain and make some random key that is stored plaintext on localStorage. I would accept a PR on this provided there are all sorts of warnings that it is not to be used in production.

**Comment by jamesdixon** [comment]
@ggozad thanks for the thoughtful reply!

What you said makes a lot of sense; people will undoubtedly end up using an insecure version :)

I believe I'll stick with using a local mock that uses localStorage when in the browser.

Thank you!
