### ISSUE TITLE
ios: Keychain access denied when launched from notification

### ISSUE THREAD

**Issue by Alex-Sessler** [Crypho/cordova-plugin-secure-storage#24]
I'm using the plugin to store a login token for my app. For iOS i use the keychain mode "WhenUnlockedThisDeviceOnly". When the app is terminated and launched through a notification, I immediately use the plugin to get the token from the Keychain, but it always fails with the error "errSecInteractionNotAllowed".

This is the Code that i use for launching the app on notification (different plugin):

```
- (void)didReceiveLocalNotification:(NSNotification *)notification
{
    if ([UIApplication sharedApplication].applicationState == UIApplicationStateInactive) {
        UILocalNotification *localNotification = notification.object;
        if (localNotification) {
            [self forwardLocalNotification:localNotification];
        }
    }
}

- (void)forwardLocalNotification:(UILocalNotification *)localNotification
{
    NSDictionary *dict = [NSDictionary dictionaryWithObject:[NSArray arrayWithObject:localNotification.userInfo] forKey:@"notifications"];
    
    [self sendSuccessfulMessageBackToJSWithData:dict andCallbackId:notificationListenerCallbackId alive:YES];
    if (isBadgingEnabled) {
        [UIApplication sharedApplication].applicationIconBadgeNumber -= 1;
    }
}

-(void)sendSuccessfulMessageBackToJSWithData:(NSDictionary *)jsonObj andCallbackId:(NSString *)callbackId alive:(BOOL)isAlive
{
    // Create an instance of CDVPluginResult, with an OK status code.
    // Set the return message as the Dictionary object (jsonObj) to be serialized as JSON in the browser
    CDVPluginResult *pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsDictionary:jsonObj];
    [pluginResult setKeepCallbackAsBool:isAlive];
    
    // Execute sendPluginResult on this plugin's commandDelegate, passing in the instance of CDVPluginResult
    [self.commandDelegate sendPluginResult:pluginResult callbackId:callbackId];
}
```

**Comment by ggozad** [comment]
Has the plugin been initialized? I am guessing not since you respond natively to the notification...

**Comment by Alex-Sessler** [comment]
Does the plugin even need any initialization on ios? The constructor doesn't seem to do much except set the service. But yes, the success callback is executed before the get call is done.

**Comment by ggozad** [comment]
All cordova plugins need initialization for the bridge to work.
But since you do things natively, you might have more luck with accessing the keychain natively as well. For iOS we barely use https://github.com/soffes/SSKeychain to do so.

**Comment by chrigi** [comment]
@Alex-Sessler wrote that he initializes the plugin after the `onDeviceReady` event was fired, so Cordova did initialize the plugins. According to your `securestorage.js` code, there is not further initialization necessary after calling the SecureStorage constructor as you immediately call the success function:
`
var SecureStorageiOS = function (success, error, service) {
    this.service = service;
    setTimeout(success, 0);
    return this;
};
`

We don't try to do anything natively. The Objective-C code above is just to show you how the app is launched when a user clicks the notification.
As stated by @Alex-Sessler the issue is that if there is a notification present and the cordova app is in a terminated state, the app will be launched by clicking on the notification (native code from 1st post) but in this state, we can't access the KeyChain in our cordova app. 
Launching the app by clicking on the icon or selecting the notification when the app is paused or running does not have this issue. We are trying to figure out if this is an issue with the Plugin, Cordova or the method how the app is launched by the native code.

**Comment by ggozad** [comment]
I see. It wasn't clear to me that the onDeviceReady was fired. 
I am not sure why this would happen. In our own product Crypho we do the same thing and can access the keychain just fine.
Would it be possible to create a simple test-case with pinned versions and see if it is reproducable?

**Comment by Alex-Sessler** [comment]
The latest changes (moving the work to threads) fixed this issue for me.

**Comment by ggozad** [comment]
awesome :)
